apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-29T21:10:52Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "9553"
  uid: 0429ec7a-3f8d-4a0d-98f6-e2efe6b0f55d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.169.24
  clusterIPs:
  - 10.106.169.24
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32045
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
